
spring:
  datasource:
    username: sa
    password: 111111
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=mydatas
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

#mybatis配置
mybatis:
  typeAliasesPackage: com.dingler.pojo
  mapperLocations: classpath:mybatis/mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml