spring:
  datasource:
    url: jdbc:postgresql://192.168.43.10:5432/myproject?useSSL=false
    username: postgres
    password: 1111
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: update
      #控制台显示sql语句
      show_sql: true
